### ISSUE TITLE
BBHTv2  'source ~/.bash_profile' issue

### ISSUE THREAD

**Issue by Suprit-hub** [unethicalnoob/BBHTv2#10]
I had tried a lot installing BBHTv2 in my VM box as well as in VMware . In kali linux as well as parrot os , but it displays same issue again and again .
It shows the below error all time . Please let me know any solution for this.
Thanks!!

[+] Installing Miscellaneous tools 
 use the command 'source ~/.bash_profile' for the shell functions to work 

      ALL THE THANKS TO THE BEST PEOPLE OF THE INFOSEC COMMUNITY

**Comment by unethicalnoob** [comment]
It is not an error. It is rather a suggestion to make functions work.
