### ISSUE TITLE
stuck while installing bbhtv2.1.sh

### ISSUE THREAD

**Issue by strider7gearhead** [unethicalnoob/BBHTv2#12]
While executing the command ./bbhtv2.1.sh 
it says installing '[+] Updating and installing dependencies' and it will stuck at this process. No more further process is executing.
<img width="375" alt="image" src="https://user-images.githubusercontent.com/94772625/194900207-0857ccad-b3d0-478a-9967-9ac91c7d9aea.png">

**Comment by unethicalnoob** [comment]
This was caused because the sqlmap installation was waiting for user input. This has been fixed in #11
