### ISSUE TITLE
~/.bash_profile empty

### ISSUE THREAD

**Issue by NeelMunot** [unethicalnoob/BBHTv2#19]
Hi,

I ran BBHTV2.1_ubuntu.sh. This script doesn't run on Ubuntu. It gives the error :

![2023-12-19_15-04](https://github.com/unethicalnoob/BBHTv2/assets/91302244/37ff761e-969b-4d7d-b44f-600318d31639)

I found the solution here : [https://stackoverflow.com/questions/14219092/bash-script-bin-bashm-bad-interpreter-no-such-file-or-directory](url)

The second issue that I faced was the bash_profile  file was empty. The link in the bbhtv2.1_ubuntu.sh file [https://raw.githubusercontent.com/unethicalnoob/aliases/master/bashprofile](url)  is invalid. It gives 403 not found error.

**Comment by unethicalnoob** [comment]
Please use the spark tool. It is the new one.
